# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WowJobTb',
            fields=[
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True)),
                ('mod_dt', models.DateTimeField(auto_now=True, db_column='mod_dt', null=True)),
                ('use', models.BooleanField(db_column='use', default=True)),
                ('id', models.BigAutoField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('job_cd', models.CharField(blank=True, db_column='job_cd', default='', max_length=20)),
                ('name', models.CharField(blank=True, db_column='name', default='', max_length=255)),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=255)),
                ('upper_job_cd', models.CharField(blank=True, db_column='upper_job_cd', default='', max_length=20)),
                ('order', models.IntegerField(blank=True, db_column='order', default=0, null=True)),
            ],
            options={
                'db_table': 'wow_job_tb',
            },
        ),
        migrations.CreateModel(
            name='WowProSkillTb',
            fields=[
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True)),
                ('mod_dt', models.DateTimeField(auto_now=True, db_column='mod_dt', null=True)),
                ('use', models.BooleanField(db_column='use', default=True)),
                ('id', models.BigAutoField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('job_cd', models.CharField(blank=True, db_column='job_cd', default='', max_length=20)),
                ('pro_type_cd', models.CharField(blank=True, db_column='pro_type_cd', default='', max_length=20)),
                ('skill_id', models.CharField(blank=True, db_column='skill_id', default='', max_length=20)),
                ('name', models.CharField(blank=True, db_column='name', default='', max_length=255)),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=3000)),
                ('range', models.CharField(blank=True, db_column='range', default='', max_length=255)),
                ('power_cost', models.CharField(blank=True, db_column='power_cost', default='', max_length=255)),
                ('cast_time', models.CharField(blank=True, db_column='cast_time', default='', max_length=255)),
                ('cool_down', models.CharField(blank=True, db_column='cool_down', default='', max_length=255)),
                ('condition', models.CharField(blank=True, db_column='condition', default='', max_length=255)),
                ('main_img_url', models.CharField(blank=True, db_column='main_img_url', default='', max_length=255)),
                ('sub_img_url', models.CharField(blank=True, db_column='sub_img_url', default='', max_length=255)),
                ('description_url', models.CharField(blank=True, db_column='description_url', default='', max_length=255)),
                ('upper_wow_pro_skill_id', models.CharField(blank=True, db_column='upper_wow_pro_skill_id', default='', max_length=20)),
                ('order', models.IntegerField(blank=True, db_column='order', default=0, null=True)),
            ],
            options={
                'db_table': 'wow_pro_skill_tb',
            },
        ),
        migrations.CreateModel(
            name='WowProTypeTb',
            fields=[
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True)),
                ('mod_dt', models.DateTimeField(auto_now=True, db_column='mod_dt', null=True)),
                ('use', models.BooleanField(db_column='use', default=True)),
                ('id', models.BigAutoField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('pro_type_cd', models.CharField(blank=True, db_column='pro_type_cd', default='', max_length=20)),
                ('name', models.CharField(blank=True, db_column='name', default='', max_length=255)),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=255)),
                ('upper_job_cd', models.CharField(blank=True, db_column='upper_job_cd', default='', max_length=20)),
                ('order', models.IntegerField(blank=True, db_column='order', default=0, null=True)),
            ],
            options={
                'db_table': 'wow_pro_type_tb',
            },
        ),
    ]
