# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wow_skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wowproskilltb',
            name='job_cd',
        ),
        migrations.RemoveField(
            model_name='wowproskilltb',
            name='pro_type_cd',
        ),
        migrations.AddField(
            model_name='wowproskilltb',
            name='wow_job_tb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wow_skills.WowJobTb'),
        ),
        migrations.AddField(
            model_name='wowproskilltb',
            name='wow_pro_type_tb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wow_skills.WowProTypeTb'),
        ),
        migrations.AddField(
            model_name='wowprotypetb',
            name='wow_job_tb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wow_skills.WowJobTb'),
        ),
    ]
