# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wow_skills', '0002_auto_20191202_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowClassTb',
            fields=[
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True)),
                ('mod_dt', models.DateTimeField(auto_now=True, db_column='mod_dt', null=True)),
                ('use', models.BooleanField(db_column='use', default=True)),
                ('id', models.BigAutoField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('class_cd', models.CharField(blank=True, db_column='class_cd', default='', max_length=20)),
                ('name', models.CharField(blank=True, db_column='name', default='', max_length=255)),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=255)),
                ('upper_job_cd', models.CharField(blank=True, db_column='upper_job_cd', default='', max_length=20)),
                ('order', models.IntegerField(blank=True, db_column='order', default=0, null=True)),
            ],
            options={
                'db_table': 'wow_class_tb',
            },
        ),
        migrations.CreateModel(
            name='WowSpecializeTypeTb',
            fields=[
                ('reg_dt', models.DateTimeField(auto_now_add=True, db_column='reg_dt', null=True)),
                ('mod_dt', models.DateTimeField(auto_now=True, db_column='mod_dt', null=True)),
                ('use', models.BooleanField(db_column='use', default=True)),
                ('id', models.BigAutoField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('specialize_type_cd', models.CharField(blank=True, db_column='specialize_type_cd', default='', max_length=20)),
                ('name', models.CharField(blank=True, db_column='name', default='', max_length=255)),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=255)),
                ('upper_job_cd', models.CharField(blank=True, db_column='upper_job_cd', default='', max_length=20)),
                ('order', models.IntegerField(blank=True, db_column='order', default=0, null=True)),
                ('wow_class_tb', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wow_skills.WowClassTb')),
            ],
            options={
                'db_table': 'wow_specialize_type_tb',
            },
        ),
        migrations.RenameModel(
            old_name='WowProSkillTb',
            new_name='WowSpecializeSkillTb',
        ),
        migrations.RemoveField(
            model_name='wowprotypetb',
            name='wow_job_tb',
        ),
        migrations.RemoveField(
            model_name='wowspecializeskilltb',
            name='wow_job_tb',
        ),
        migrations.RemoveField(
            model_name='wowspecializeskilltb',
            name='wow_pro_type_tb',
        ),
        migrations.AlterModelTable(
            name='wowspecializeskilltb',
            table='wow_specialize_skill_tb',
        ),
        migrations.DeleteModel(
            name='WowJobTb',
        ),
        migrations.DeleteModel(
            name='WowProTypeTb',
        ),
        migrations.AddField(
            model_name='wowspecializeskilltb',
            name='wow_class_tb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wow_skills.WowClassTb'),
        ),
        migrations.AddField(
            model_name='wowspecializeskilltb',
            name='wow_specialize_type_tb',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wow_skills.WowSpecializeTypeTb'),
        ),
    ]
