# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-03 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_skills', '0003_auto_20191203_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wowspecializeskilltb',
            name='upper_wow_pro_skill_id',
        ),
        migrations.AddField(
            model_name='wowspecializeskilltb',
            name='upper_wow_specialize_skill_id',
            field=models.CharField(blank=True, db_column='upper_wow_specialize_skill_id', default='', max_length=20),
        ),
    ]
