# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-07 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wow_skills', '0004_auto_20191203_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wowspecializeskilltb',
            name='description_url',
        ),
        migrations.RemoveField(
            model_name='wowspecializeskilltb',
            name='main_img_url',
        ),
        migrations.RemoveField(
            model_name='wowspecializeskilltb',
            name='sub_img_url',
        ),
        migrations.AddField(
            model_name='wowspecializeskilltb',
            name='description_img_url',
            field=models.CharField(blank=True, db_column='description_img_url', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wowspecializeskilltb',
            name='icon',
            field=models.CharField(blank=True, db_column='icon', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wowspecializeskilltb',
            name='large_img_url',
            field=models.CharField(blank=True, db_column='large_img_url', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wowspecializeskilltb',
            name='medium_img_url',
            field=models.CharField(blank=True, db_column='medium_img_url', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wowspecializeskilltb',
            name='small_img_url',
            field=models.CharField(blank=True, db_column='small_img_url', default='', max_length=255),
        ),
    ]
