# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wow_skills', '0005_auto_20191207_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowspecializeskilltb',
            name='wow_class_tb',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_skills.WowClassTb'),
        ),
        migrations.AlterField(
            model_name='wowspecializeskilltb',
            name='wow_specialize_type_tb',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='wow_skills.WowSpecializeTypeTb'),
        ),
    ]
